apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: tap-gui-catalog-info
  description: A sample catalog for Backstage
  annotations:
    'backstage.io/techdocs-ref': url:https://github.com/weresch/tap-gui-catalogs/tree/main/blank/components
spec:
  targets:
    - ./components/tap-gui.yaml
    - ./groups/default-org.yaml
    - ./systems/tap-gui-system.yaml
    - ./domains/tap-gui-domain.yaml
